In [2]:
import numpy as np

In [5]:
L=range(1000)
%timeit[i**2 for i in L]

The slowest run took 4.95 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 263 µs per loop


In [7]:
arr = np.arange(1000)
%timeit arr**2

The slowest run took 1244.71 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.32 µs per loop


In [8]:
L=[1,2,3] #list
a=np.array(L)

In [9]:
L*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [10]:
a*3

array([3, 6, 9])

In [19]:
a = np.array([[0,1],[1,2]])
a.ndim #차원

2

In [20]:
a.shape #더 상세히 표현

(2, 2)

In [28]:
a=np.array([0,1,2,3])
b=np.array([[0,1,2,3]])
a,b,a.T,b.T #1차원은 행과 열이 바뀌지않음

(array([0, 1, 2, 3]), array([[0, 1, 2, 3]]), array([0, 1, 2, 3]), array([[0],
        [1],
        [2],
        [3]]))

In [30]:
np.arange(10) #list(range(100))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10,2) #list(range(1,10,2))

array([1, 3, 5, 7, 9])

In [38]:
np.linspace(1,6,10),\
np.linspace(1,6,10,endpoint=False) #(시작점,끝점,점의 개수)

(array([ 1.        ,  1.55555556,  2.11111111,  2.66666667,  3.22222222,
         3.77777778,  4.33333333,  4.88888889,  5.44444444,  6.        ]),
 array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5]))

In [43]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [42]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [45]:
np.eye(5) #단위행렬

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [46]:
np.diag((1,2,3,4,5))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [49]:
a = np.array([1,2,3])
np.tile(a,2) 

array([1, 2, 3, 1, 2, 3])

In [50]:
np.tile(a,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [52]:
b=np.array([[1,2],[3,4]])
np.tile(b,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [53]:
np.tile(b,(3,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [54]:
np.tile(b,(3,2,4))

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

In [55]:
a= np.arange(20)
np.reshape(a,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
a.reshape(3,6)

ValueError: cannot reshape array of size 20 into shape (3,6)

In [58]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [59]:
a.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
a = np.arange(5)
np.vstack([a+5,a*10]) , a.dtype

(array([[ 5,  6,  7,  8,  9],
        [ 0, 10, 20, 30, 40]]), dtype('int32'))

In [64]:
a = np.array([1,2.])
a.dtype

dtype('float64')

In [70]:
a=np.arange(10)
b=a.copy()
a[0]=99
a,b

(array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [71]:
a = np.arange(20)
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [75]:
idx = a % 2 == 0
a[idx] #결과값이 True인 것을 반환

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [76]:
idx = a<10
a[idx]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
a = np.diag([1,2,3])
b = np.diag([3,3,3])
a+b

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [87]:
a.dot(b) #매트릭스 연산

array([[3, 0, 0],
       [0, 6, 0],
       [0, 0, 9]])

In [88]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

21

In [92]:
a.sum(axis=0), a.sum(axis=1) #0=세로방향, 1=가로방향

(array([5, 7, 9]), array([ 6, 15]))

In [96]:
a= np.tile(np.arange(0,40,10),(3,1))
a,a.T

(array([[ 0, 10, 20, 30],
        [ 0, 10, 20, 30],
        [ 0, 10, 20, 30]]), array([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]]))

In [99]:
a = np.array([[4,3,5],[1,2,1]])
b = np.sort(a,axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [100]:
b = np.sort(a,axis=0)
b

array([[1, 2, 1],
       [4, 3, 5]])

In [101]:
a = np.array([5,2,7,3])
np.argsort(a) #순위 0-1-2-3 

array([1, 3, 0, 2], dtype=int64)

In [102]:
b = np.argsort(a)
a[b]

array([2, 3, 5, 7])

회귀분석

y=B0+B1*x+e (B0:상수, B1:계수, e:에러 )

In [108]:
#목적데이터 y / y에 영향을 미친다고 생각되는 x
x=np.random.uniform(-5,5,100)
y=2+3*x+np.random.normal(0,3,100)
y_mat = np.mat(y).T

In [ ]:
import matplotlib.pyplot as plt
plt.plot(x,y,'ro',label="x")
plt.plot(x,3*x+2,color="blue",linestyle="")
plt.legend(loc="best")

In [ ]:
import numpy.linalg as lin
x1=np.array([np,tile(1,100),x]).T
beta = np.dot(lin.inv(np.dot(x1.T,x1)),np.dot(x1.T,y))

predict = beta[0] + beta[1]*x

numpy exercise - 품질예측

In [109]:
redwine=np.loadtxt(fname='d:/winequality-red.csv',delimiter=';',skiprows=1)

In [110]:
redwine

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [111]:
redwine.shape

(1599, 12)

In [112]:
redwine.sum(axis=0)

array([ 13303.1    ,    843.985  ,    433.29   ,   4059.55   ,
          139.859  ,  25384.     ,  74302.     ,   1593.79794,
         5294.47   ,   1052.38   ,  16666.35   ,   9012.     ])

In [113]:
redwine.mean(axis=0)

array([  8.31963727,   0.52782051,   0.27097561,   2.5388055 ,
         0.08746654,  15.87492183,  46.46779237,   0.99674668,
         3.3111132 ,   0.65814884,  10.42298311,   5.63602251])

In [114]:
redwine.max(axis=0)

array([  15.9    ,    1.58   ,    1.     ,   15.5    ,    0.611  ,
         72.     ,  289.     ,    1.00369,    4.01   ,    2.     ,
         14.9    ,    8.     ])

In [115]:
redwine.std(axis=0)

array([  1.74055180e+00,   1.79003704e-01,   1.94740214e-01,
         1.40948711e+00,   4.70505826e-02,   1.04568856e+01,
         3.28850367e+01,   1.88674370e-03,   1.54338181e-01,
         1.69453967e-01,   1.06533430e+00,   8.07316877e-01])

In [116]:
redwine.shape

(1599, 12)

In [121]:
import numpy.linalg as lin

y= redwine[:,11]
x= redwine[:,range(11)]

#np.tile(1,len(x)) :데이터 수만큼 1이 있는 array생성 - 상수
x1=np.hstack([np.array([np.tile(1,len(x))]).T,x])

beta = np.dot(lin.inv(np.dot(x1.T,x1)),np.dot(x1.T,y))

predict = beta[0] + beta[1]*x

pandas

In [122]:
import pandas as pd

In [124]:
a = pd.Series([1,2,3,4])
a , a.values

(0    1
 1    2
 2    3
 3    4
 dtype: int64, array([1, 2, 3, 4], dtype=int64))

In [125]:
a = pd.Series([1,2,3,4],index=['b','d','a','c'])
a

b    1
d    2
a    3
c    4
dtype: int64

In [127]:
a[:'a']

b    1
d    2
a    3
dtype: int64

In [128]:
a[a>2]

a    3
c    4
dtype: int64

In [129]:
'a' in a, 'e' in a #인덱스 명시 가능 

(True, False)

In [132]:
sdata={'Ohio':35000,'Texas':71000}
a = pd.Series(sdata)
a

Ohio     35000
Texas    71000
dtype: int64

In [134]:
states = ['California','Oregon','Texas']
a = pd.Series(sdata,index=states)
a

California        NaN
Oregon            NaN
Texas         71000.0
dtype: float64

In [136]:
pd.notnull(a)

California    False
Oregon        False
Texas          True
dtype: bool

In [137]:
a.drop('California')

Oregon        NaN
Texas     71000.0
dtype: float64